### ISSUE TITLE
[BUG] Shields from "M&B Battlegear 2 - Bullseye" render bug

### ISSUE THREAD

**Issue by TheGoldenAdmin** [Armourers-Workshop/Armourers-Workshop#338]
I have added a wooden shield as a sword type (sword:battlegear2:shield.wood), made a model and found out that in f5 mode, the shield model renders the "supposedly unseen" sides of the model and doesn't render the "camera facing" sides of the model.
In other words, the rendering of the faces is "inverted" in f5 mode.

MC version: _ForgeOptiFine 1.7.10_
Armourer's Workshop version: _1.7.10-0.48.3_
Mine & Blade Battlegear 2 - Bullseye version: _1.0.8.2 (1.7.10)_

**Comment by ZayHolt** [comment]
This bug doesn't only happen with the shields of this mod, it happens with any "item" you set as skinnable, for example, I set the minecraft:diamond as skinabble and the same problem you reported happened. This bug has already been fixed in the 1.12.2 version, but I believe it would be great if this bug was fixed in the 1.7.10 version because there are several players who only play in this version like me and so many others.

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
