### ISSUE TITLE
[CRASH] There was a critical exception handling a packet on channel arms-ws

### ISSUE THREAD

**Issue by yirip** [Armourers-Workshop/Armourers-Workshop#358]
**To Reproduce**
Steps to reproduce the crash:

1. Launch 1.12.2 Forge
2. Try to join server (Magma)
3. Screen briefly shows up
4. Error message "Connection Lost. A fatal error has occurred, this connection is terminated'

**Crash log**
https://pastebin.com/SNAgbfUw
(Server side)

**Screenshots**

**Additional context**
Once you rejoin the server, it won't happen again for a while.

**Comment by Meeeeero** [comment]
This also happened on our server.
Seems like it has something to do with the multiverse.
It usually happens when the player tries to load skins as well as open wardrobe GUI.
If you are lucky enough, the skin loaded successfully before you get kicked out of the server, it won't happen... at least for a while. Not until the player tries to load the next skin.

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
