### ISSUE TITLE
Armourers compatibility with epic fight mod or any mod with player animation[Feature]

### ISSUE THREAD

**Issue by christhefish4** [Armourers-Workshop/Armourers-Workshop#369]
just a thought

**Comment by DoomRater** [comment]
Player animations are a fickle thing.  From what I can see, there is limited synergy with Customizable Player Models animations  and Quark's Emotes, but those same animations also tend to be hit-or-miss with Extra Bit Manipulation's cosmetic armor options.  There might be something that can be adjusted as far as what the arms on a chest model of Armourer's Workshop actually attach to, but I'm also not familiar with the codebase as to know what.

My basis for stating that is I can see similar issues with animations on Botania's armor models (an issue I believe has been corrected in later versions of Botania, and something I should attempt to backport if I can) as well as Thaumcraft 6's armor models, which appear to have their own animation overlaid the vanilla armor system instead of being attached to the Player model and using that.  Or it might be that they were attached incorrectly to the wrong model part.  Without looking at the code and seeing the proper fix, I can't say.

**Comment by SAGESSE-CN** [comment]
Fixed in 1.16.5/1.18.2 beta.6+
