### ISSUE TITLE
[BUG] I don't see my skin in minecraft

### ISSUE THREAD

**Issue by ItsTimsonn** [Armourers-Workshop/Armourers-Workshop#375]
I'm playing on version 1.7.10 and 0.48.3 of the mod, but when I log into the game I can't see my skin when I press F5. Please help me solve this problem

**Comment by TroubleDarkness** [comment]
If you're talking about HD skin, it will not appear. If not, you can change skin render method in Armourer's Workshop configuration file. Line `texturePainting` Try any other value. If you're using HD skin, set it to `2`, but some of Armourer's Workshop funcionality will be lost.

Once (or more) RiskyKen already answered about this problem:

_"HD skins are not supported in the 1.7.10 version of the mod and probably never will be because it's not getting big updates anymore"_

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
