### ISSUE TITLE
[Feature] Support for Easy NPCs

### ISSUE THREAD

**Issue by MarkusBordihn** [Armourers-Workshop/Armourers-Workshop#435]
Dear Armourers-Workshop Developer,
hope you are doing well. I got a lot of request for my Easy NPC mod to support Armourers Workshop.
I like the mod and so I'm very open to do the needed implementation steps.

**Describe the solution you'd like**
Possibility to use the Armourers Workshop mod with the Easy NPCs over the NPC wand or to open the custom menu from the NPC wand.
See: https://github.com/MarkusBordihn/BOs-Easy-NPC/tree/1.18.2

**Describe alternatives you've considered**
I tried to setup a armourers_workshop/skin/profile/easy_npc.json data file to add the skin profiles myself.
Unfortunately that doesn't worked, because the `DataPackManager` is limited and will not scan other mods `data` folder for the corresponding informations.
I additional tried to add a EntityProfile over ModEntityProfiles directly, but there is no public method or easy way to do this over the code.
I also found no clear developer guide, which kind of entity information and renderer adjustments are needed to use the Armourers Workshop layers.

**Additional context**
I'm happy to make corresponding adjustments within the Easy NPC mod ,  if there is a need.

If there is a way to implement the support within my mod it would be great if you could provide me some pointers.
My idea was to provide a specific Easy NPC Entiity which could be used with this mod, or adding the support for compatible entities like human, villager, ...

I want to add the support first for 1.18.2 and implement the needed changes to the other versions later.
Happy to create a PR, if there is any work I could help with. Thanks.

**Comment by SAGESSE-CN** [comment]
Thanks you contact our, and yes at present, although the profile is stored in the data directory, but it is a mod internal file. 

It is special because it must handle some patches before joining the server, the server   data pack is too late for we.
and the it modify easy, but it requires the programmer checks model such as using custom rendering or using model part.

you made a good suggestion. In later versions, we will consider checking the data in other jars to support the extension.

In your case, you just provide entity id to we of the needs support.

**Comment by SAGESSE-CN** [comment]
If you need to test it, you can modify the aw jar directly.

**Comment by MarkusBordihn** [comment]
Thanks for the fast response. I was able to make this work on my side and crated a PR for the basic Easy NPC entities.

It would be great if you could update the 1.18.2 and higher versions on Curseforge as soon this PR is merged.

Thanks a lot and keep up the good work. ;)
